language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update 
  - sudo apt-get install -y libsdl-dev 
  - sudo apt-get install -y libportaudio-dev
script: cmake -DCMAKE_BUILD_TYPE=Release . && make

notifications:
  email:
    recipients:
      - travis-ci@luchenlabs.com
    on_success: change
    on_failure: always

